import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    name: "Dadaism Concept",
    original_price: 149,
    discounted_price: 99,
    category_name: "Abstract",
    is_stock: true,
    rating: 4.3,
    reviews: 109,
    description:
      "It was defined by a common mentality. Dadaist artists shared an intellectual and emotional desire to confront the absurdity of human culture. Dadaism manifested simultaneously in Zurich and New York starting around the year 1915 and soon spread throughout the Western art world",
    trending: true,
    size: 5,
    img: "/assets/images/products-images/Abstract-1.avif",
  },

  {
    _id: uuid(),
    name: "Abstract Collage",
    original_price: 130,
    discounted_price: 99,
    category_name: "Abstract",
    is_stock: true,
    rating: 4.1,
    reviews: 129,
    description:
      "Abstract colorful background with different human faces Contemporary art collage.",
    trending: true,
    size: 7,
    img: "/assets/images/products-images/Abstract-2.jpg",
  },
  {
    _id: uuid(),
    name: "The three women",
    original_price: 199,
    discounted_price: 79,
    category_name: "Abstract",
    is_stock: true,
    rating: 2.7,
    reviews: 19,
    description:
      "There are three women standing together in a line with a orange background.",
    trending: false,
    size: 4,
    img: "/assets/images/products-images/Abstract-3.avif",
  },
  {
    _id: uuid(),
    name: "Autism Awareness",
    original_price: 299,
    discounted_price: 199,
    category_name: "Abstract",
    is_stock: true,
    rating: 3.3,
    reviews: 130,
    description:
      "Autism day awareness with colourful portrait.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/Abstract-4.avif",
  },
  {
    _id: uuid(),
    name: "Wall of Faces",
    original_price: 399,
    discounted_price: 299,
    category_name: "Abstract",
    is_stock: true,
    rating: 4.5,
    reviews: 109,
    description:
      "A close up of a colorful wall with many different faces.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/Abstract-5.avif",
  },
  {
    _id: uuid(),
    name: "Trad pattern design",
    original_price: 99,
    discounted_price: 89,
    category_name: "Abstract",
    is_stock: true,
    rating: 3.4,
    reviews: 39,
    description:
      "African Traditional Pattern Design For background Social Media Packaging Industry And Digital Media.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/Abstract-6.avif",
  },
  {
    _id: uuid(),
    name: "A-Dada",
    original_price: 99,
    discounted_price: 89,
    category_name: "Abstract",
    is_stock: true,
    rating: 3.4,
    reviews: 39,
    description:
      "Abstract dadaism concept.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/Abstract-7.jpg",
  },

  {
    _id: uuid(),
    name: "Healthy food",
    original_price: 399,
    discounted_price: 299,
    category_name: "Oil_Painting",
    is_stock: true,
    rating: 3.6,
    reviews: 32,
    description:
      "World health day celebration with healthy food.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/Oil1.avif",
  },
  {
    _id: uuid(),
    name: "sculptures and pottery",
    original_price: 599,
    discounted_price: 499,
    category_name: "Oil_Painting",
    is_stock: true,
    rating: 4.6,
    reviews: 1094,
    description:
      "Collection of wooden sculptures and pottery.",
    trending: true,
    size: 7,
    img: "/assets/images/products-images/Oil2.avif",
  },
  {
    _id: uuid(),
    name: "Woman's Potrait",
    original_price: 699,
    discounted_price: 599,
    category_name: "Oil_Painting",
    is_stock: true,
    rating: 4.5,
    reviews: 166,
    description:
      "Painting of woman's portrait.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/Oil3.avif",
  },
  {
    _id: uuid(),
    name: "Dark Elites",
    original_price: 899,
    discounted_price: 799,
    category_name: "Oil_Painting",
    is_stock: true,
    rating: 4.6,
    reviews: 47,
    description:
      "An oil painting depicting african warriors and culture.",
    trending: false,
    size: 10,
    img: "/assets/images/products-images/Oil4.avif",
  },
  {
    _id: uuid(),
    name: "Goddess Osun",
    original_price: 399,
    discounted_price: 299,
    category_name: "Oil_Painting",
    is_stock: true,
    rating: 3.3,
    reviews: 200,
    description:
      "The African goddess Oshun addressing warmth and preparation.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/Oil5.jpg",
  },
  {
    _id: uuid(),
    name: "loving connection",
    original_price: 999,
    discounted_price: 899,
    category_name: "Oil_Painting",
    is_stock: true,
    rating: 4.0,
    reviews: 222,
    description:
      "Oil painting depicting an african family.",
    trending: false,
    size: 6,
    img: "/assets/images/products-images/Oil6.avif",
  },
  {
    _id: uuid(),
    name: "Geobony",
    original_price: 699,
    discounted_price: 599,
    category_name: "Digital_Painting",
    is_stock: false,
    rating: 3.1,
    reviews: 29,
    description:
      "Abstract Portrait of a Woman with Colorful Makeup and Geometric Shapes.",
    trending: true,
    size: 6,
    img: "/assets/images/products-images/Digital1.avif",
  },
  {
    _id: uuid(),
    name: "Black Gold",
    original_price: 999,
    discounted_price: 899,
    category_name: "Digital_Painting",
    is_stock: true,
    rating: 2.3,
    reviews: 25,
    description:
      "A woman with gold painted face paint.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/Digital2.avif",
  },
  {
    _id: uuid(),
    name: "Radiance",
    original_price: 799,
    discounted_price: 699,
    category_name: "Digital_Painting",
    is_stock: false,
    rating: 1.7,
    reviews: 14,
    description:
      "Brightly colored portrait of a woman with a turban and earrings.",
    trending: false,
    size: 8,
    img: "/assets/images/products-images/Digital3.jpg",
  },
  {
    _id: uuid(),
    name: "Flow",
    original_price: 399,
    discounted_price: 299,
    category_name: "Digital_Painting",
    is_stock: true,
    rating: 4.3,
    reviews: 144,
    description:
      "Beauty portrait of afro woman with ethnic makeup.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/Digital4.jpg",
  },
  {
    _id: uuid(),
    name: "Sunset Lilac",
    original_price: 999,
    discounted_price: 999,
    category_name: "Digital_Painting",
    is_stock: false,
    rating: 4.2,
    reviews: 89,
    description:
      "Pretty Black Woman Portrait.",
    trending: true,
    size: 9,
    img: "/assets/images/products-images/Digital5.avif",
  },
  {
    _id: uuid(),
    name: "Sunset Surfer",
    original_price: 1299,
    discounted_price: 1199,
    category_name: "Digital_Painting",
    is_stock: false,
    rating: 4.9,
    reviews: 398,
    description:
      "A woman with yellow sunglasses and a black jacket that says'black and yellow'.",
    trending: false,
    size: 6,
    img: "/assets/images/products-images/Digital6.jpg",
  },
  {
    _id: uuid(),
    name: "Sun Goddess",
    original_price: 199,
    discounted_price: 99,
    category_name: "Realism",
    is_stock: false,
    rating: 4.7,
    reviews: 433,
    description:
      "Radiant depiction of empowered female sun goddess.",
    trending: true,
    size: 5,
    img: "/assets/images/products-images/Realism1.avif",
  },
  {
    _id: uuid(),
    name: "Collective mind",
    original_price: 79,
    discounted_price: 69,
    category_name: "Realism",
    is_stock: true,
    rating: 4.4,
    reviews: 19,
    description:
      "Representation of collective mind process and concept in realism art style.",
    trending: false,
    size: 6,
    img: "/assets/images/products-images/Realism2.avif",
  },
  {
    _id: uuid(),
    name: "Nightshade Crimson",
    original_price: 1499,
    discounted_price: 999,
    category_name: "Realism",
    is_stock: false,
    rating: 4.3,
    reviews: 132,
    description:
      "Realism portrait with light effects.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/Realism3.avif",
  },
  {
    _id: uuid(),
    name: "The Art and Artist",
    original_price: 699,
    discounted_price: 599,
    category_name: "Realism",
    is_stock: true,
    rating: 5.0,
    reviews: 132,
    description:
      "Portrait of person with geometric surreal animal.",
    trending: true,
    size: 7,
    img: "/assets/images/products-images/Realism4.avif",
  },

  {
    _id: uuid(),
    name: "The end of heartache",
    original_price: 299,
    discounted_price: 199,
    category_name: "Realism",
    is_stock: false,
    rating: 4.8,
    reviews: 654,
    description:
      "Juneteenth celebration with symbolic representation of the end of slavery in the united states.",
    trending: true,
    size: 8,
    img: "/assets/images/products-images/Realism5.avif",
  },
  {
    _id: uuid(),
    name: "Empowerment",
    original_price: 499,
    discounted_price: 399,
    category_name: "Realism",
    is_stock: true,
    rating: 3.9,
    reviews: 65,
    description:
      "Close up on hand wearing chains.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/Realism6.avif",
  },
  {
    _id: uuid(),
    name: "Mannie",
    original_price: 1499,
    discounted_price: 999,
    category_name: "3D_Art",
    is_stock: true,
    rating: 3.5,
    reviews: 43,
    description:
      "A mannequin with a yellow shirt and orange striped headband.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/3D1.jpg",
  },
  {
    _id: uuid(),
    name: "Wooden Sculpture",
    original_price: 999,
    discounted_price: 899,
    category_name: "3D_Art",
    is_stock: false,
    rating: 2.5,
    reviews: 99,
    description:
      "Handcrafted wooden decorative sculpture.",
    trending: true,
    size: 5,
    img: "/assets/images/products-images/3D2.avif",
  },
  {
    _id: uuid(),
    name: "Togetherness",
    original_price: 299,
    discounted_price: 199,
    category_name: "3D_Art",
    is_stock: false,
    rating: 4.9,
    reviews: 1809,
    description:
      "A 3D poster for Black History Month that showcases a virtual sculpture of the African continent.",
    trending: true,
    size: 6,
    img: "/assets/images/products-images/3D3.avif",
  },
  {
    _id: uuid(),
    name: "Unity",
    original_price: 399,
    discounted_price: 299,
    category_name: "3D_Art",
    is_stock: true,
    rating: 4.0,
    reviews: 65,
    description:
      "A 3D poster for Black History Month that showcases a virtual sculpture of the African continent.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/3D4.jpg",
  },
  {
    _id: uuid(),
    name: "Future masks",
    original_price: 599,
    discounted_price: 499,
    category_name: "3D_Art",
    is_stock: true,
    rating: 4.8,
    reviews: 78,
    description:
      "Traditional African masks morphing into futuristic 00127 00.",
    trending: false,
    size: 12,
    img: "/assets/images/products-images/3D5.jpg",
  },
  {
    _id: uuid(),
    name: "Wooden Sculptures",
    original_price: 1499,
    discounted_price: 1399,
    category_name: "3D_Art",
    is_stock: true,
    rating: 5.0,
    reviews: 45,
    description:
      "Handcrafted wooden decorative sculpture.",
    trending: false,
    size: 11,
    img: "/assets/images/products-images/3D6.avif",
  },
  {
    _id: uuid(),
    name: "Party Time",
    original_price: 799,
    discounted_price: 699,
    category_name: "Pixel_Art",
    is_stock: true,
    rating: 3.5,
    reviews: 123,
    description:
      "Domestic life illustrated.",
    trending: false,
    size: 10,
    img: "/assets/images/products-images/Pixel1.avif",
  },
  {
    _id: uuid(),
    name: "Meal Time",
    original_price: 1199,
    discounted_price: 1099,
    category_name: "Pixel_Art",
    is_stock: true,
    rating: 4.2,
    reviews: 987,
    description:
      "Domestic life illustrated.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/Pixel2.jpg",
  },
  {
    _id: uuid(),
    name: "Feeling the Frow",
    original_price: 399,
    discounted_price: 299,
    category_name: "Pixel_Art",
    is_stock: true,
    rating: 4.3,
    reviews: 654,
    description:
      "A cartoon illustration of a woman with glasses and a hair style.",
    trending: false,
    size: 8,
    img: "/assets/images/products-images/Pixel3.jpg",
  },
  {
    _id: uuid(),
    name: "Iconic",
    original_price: 199,
    discounted_price: 99,
    category_name: "Pixel_Art",
    is_stock: false,
    rating: 4.3,
    reviews: 89,
    description:
      "Diverse Pixel Art Character Collection Featuring Iconic Figures.",
    trending: true,
    size: 9,
    img: "/assets/images/products-images/Pixel4.jpg",
  },
  {
    _id: uuid(),
    name: "Vacation Time",
    original_price: 1099,
    discounted_price: 999,
    category_name: "Pixel_Art",
    is_stock: false,
    rating: 4.6,
    reviews: 43,
    description:
      "Domestic life illustrated",
    trending: true,
    size: 8,
    img: "/assets/images/products-images/Pixel5.avif",
  },
  {
    _id: uuid(),
    name: "AfroFuturism",
    original_price: 1699,
    discounted_price: 1599,
    category_name: "Pixel_Art",
    is_stock: true,
    rating: 4.7,
    reviews: 76,
    description:
      "An afrofuturism illustration in the style of psychedelic overload.",
    trending: true,
    size: 6,
    img: "/assets/images/products-images/Pixel6.jpg",
  },
  {
    _id: uuid(),
    name: "Celestial Embrace",
    original_price: 1699,
    discounted_price: 1599,
    category_name: "Fantasy",
    is_stock: true,
    rating: 4.8,
    reviews: 89,
    description:
      "There is a woman with a feathered headdress and a feathered dress.",
    trending: false,
    size: 8,
    img: "/assets/images/products-images/Fantasy1.jpg",
  },
  {
    _id: uuid(),
    name: "Kitten Eyes",
    original_price: 1799,
    discounted_price: 1699,
    category_name: "Fantasy",
    is_stock: true,
    rating: 1.2,
    reviews: 78,
    description:
      "A cute kitten.",
    trending: true,
    size: 9,
    img: "/assets/images/products-images/Fantasy2.jpg",
  },
  {
    _id: uuid(),
    name: "Ocean's Dream",
    original_price: 1899,
    discounted_price: 1799,
    category_name: "Fantasy",
    is_stock: true,
    rating: 1.6,
    reviews: 43,
    description:
      "Dreamy young merman underwater.",
    trending: false,
    size: 10,
    img: "/assets/images/products-images/Fantasy3.avif",
  },
  {
    _id: uuid(),
    name: "Anemona Fedora",
    original_price: 1499,
    discounted_price: 1399,
    category_name: "Fantasy",
    is_stock: true,
    rating: 2.6,
    reviews: 54,
    description:
      "Portrait of surreal sea creature.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/Fantasy4.avif",
  },
  {
    _id: uuid(),
    name: "Infernal Glory",
    original_price: 1999,
    discounted_price: 1899,
    category_name: "Fantasy",
    is_stock: true,
    rating: 2.4,
    reviews: 9,
    description:
      "Woman with dragon fantasy scene.",
    trending: true,
    size: 6,
    img: "/assets/images/products-images/Fantasy5.avif",
  },
  {
    _id: uuid(),
    name: "Silver Lining",
    original_price: 2099,
    discounted_price: 1999,
    category_name: "Fantasy",
    is_stock: true,
    rating: 4.9,
    reviews: 555,
    description:
      "Futuristic fantasy portrait with costume.",
    trending: false,
    size: 8,
    img: "/assets/images/products-images/Fantasy6.avif",
  },
  {
    _id: uuid(),
    name: "The Explorer",
    original_price: 2199,
    discounted_price: 2099,
    category_name: "Sci_Fi",
    is_stock: true,
    rating: 4.8,
    reviews: 325,
    description:
      "Futuristic fantasy portrait with costume.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/Scifi1.avif",
  },
  {
    _id: uuid(),
    name: "Singularity",
    original_price: 1399,
    discounted_price: 1299,
    category_name: "Sci_Fi",
    is_stock: false,
    rating: 4.6,
    reviews: 986,
    description:
      "Digital art of ai technology background.",
    trending: true,
    size: 5,
    img: "/assets/images/products-images/Scifi2.avif",
  },
  {
    _id: uuid(),
    name: "The Hacker",
    original_price: 1199,
    discounted_price: 999,
    category_name: "Sci_Fi",
    is_stock: false,
    rating: 3.2,
    reviews: 777,
    description:
      "Portrait of technologically advanced female humanoid.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/Scifi3.jpg",
  },
  {
    _id: uuid(),
    name: "The Oracle",
    original_price: 1499,
    discounted_price: 1399,
    category_name: "Sci_Fi",
    is_stock: true,
    rating: 3.8,
    reviews: 432,
    description:
      "Futuristic fusion young black woman with cybernetic style and artistic expression.",
    trending: true,
    size: 8,
    img: "/assets/images/products-images/Scifi4.jpg",
  },
  {
    _id: uuid(),
    name: "The Hunter",
    original_price: 1099,
    discounted_price: 999,
    category_name: "Sci_Fi",
    is_stock: true,
    rating: 3.7,
    reviews: 457,
    description:
      "Shoot of fantastic futuristic african bounty hunter.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/Scifi5.avif",
  },
  {
    _id: uuid(),
    name: "Upgrade",
    original_price: 999,
    discounted_price: 899,
    category_name: "Sci_Fi",
    is_stock: true,
    rating: 3.4,
    reviews: 34,
    description:
      "Cyberpunk woman at golden hour near the windows courtains enhancing herself.",
    trending: false,
    size: 10,
    img: "/assets/images/products-images/Scifi6.avif",
  },
  {
    _id: uuid(),
    name: "Floral Serenity",
    original_price: 799,
    discounted_price: 599,
    category_name: "Floral",
    is_stock: true,
    rating: 5.0,
    reviews: 976,
    description:
      "Cartoon Tree illustration.",
    trending: false,
    size: 12,
    img: "/assets/images/products-images/Floral1.avif",
  },
  {
    _id: uuid(),
    name: "Miss Violet",
    original_price: 699,
    discounted_price: 599,
    category_name: "Floral",
    is_stock: true,
    rating: 4.8,
    reviews: 322,
    description:
      "Digital art 8m women strike movement.",
    trending: false,
    size: 11,
    img: "/assets/images/products-images/Floral2.jpg",
  },
  {
    _id: uuid(),
    name: "Mother nature",
    original_price: 499,
    discounted_price: 399,
    category_name: "Floral",
    is_stock: false,
    rating: 4.5,
    reviews: 56,
    description:
      "A young black girl with flower fantasy digital art.",
    trending: false,
    size: 10,
    img: "/assets/images/products-images/Floral3.jpg",
  },
  {
    _id: uuid(),
    name: "Lady in Bloom",
    original_price: 99,
    discounted_price: 89,
    category_name: "Floral",
    is_stock: false,
    rating: 4.1,
    reviews: 345,
    description:
      "A woman adorned with stunning floral patterns in shades of red and pink.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/Floral4.jpg",
  },

  {
    _id: uuid(),
    name: "Twilight Tranquility",
    original_price: 599,
    discounted_price: 499,
    category_name: "Floral",
    is_stock: true,
    rating: 4.8,
    reviews: 1609,
    description:
      "Muscular Sexy Handsome Ripped Shredded Shirtless Black Man Bathing in a Bathtub Full of Flowers.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/Floral5.jpg",
  },
  {
    _id: uuid(),
    name: "Sunflower Dream",
    original_price: 149,
    discounted_price: 99,
    category_name: "Floral",
    is_stock: true,
    rating: 4.3,
    reviews: 109,
    description:
      "Child with autism living in fantasy world.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/Floral6.avif",
  },

  {
    _id: uuid(),
    name: "Patricia's Paradise",
    original_price: 1299,
    discounted_price: 1199,
    category_name: "Animals_and_Pets",
    is_stock: true,
    rating: 4.9,
    reviews: 65,
    description:
      "Medium shot woman posing with parrot.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/Pet1.avif",
  },
  {
    _id: uuid(),
    name: "Royal Loyalty",
    original_price: 1799,
    discounted_price: 1699,
    category_name: "Animals_and_Pets",
    is_stock: true,
    rating: 4.6,
    reviews: 765,
    description:
      "Super Realistic Still Movie Shot of an African Queen.",
    trending: false,
    size: 8,
    img: "/assets/images/products-images/Pet2.jpg",
  },
  {
    _id: uuid(),
    name: "Deadly Duo",
    original_price: 1099,
    discounted_price: 999,
    category_name: "Animals_and_Pets",
    is_stock: true,
    rating: 4.7,
    reviews: 45,
    description:
      "An African elite woman warrior walking with a panther forging her path of self-discovery.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/Pet3.jpg",
  },
  {
    _id: uuid(),
    name: "Call of the Wild",
    original_price: 99,
    discounted_price: 89,
    category_name: "Animals_and_Pets",
    is_stock: true,
    rating: 4.8,
    reviews: 99,
    description:
      "When nature calls, you answer.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/Pet4.jpg",
  },

  {
    _id: uuid(),
    name: "Emerald Glare",
    original_price: 1499,
    discounted_price: 999,
    category_name: "Animals_and_Pets",
    is_stock: false,
    rating: 4.9,
    reviews: 543,
    description:
      "A black woman with sunglasses and sunflower Afro hair standing beside a white leopard.",
    trending: false,
    size: 8,
    img: "/assets/images/products-images/Pet5.jpg",
  },
  {
    _id: uuid(),
    name: "Falcon Fervor",
    original_price: 1599,
    discounted_price: 1499,
    category_name: "Animals_and_Pets",
    is_stock: false,
    rating: 3.0,
    reviews: 78,
    description:
      "Photograph of a dark skinned woman with a hawk.",
    trending: true,
    size: 11,
    img: "/assets/images/products-images/Pet6.jpg",
  },
  {
    _id: uuid(),
    name: "Monochrome Dome",
    original_price: 1399,
    discounted_price: 1299,
    category_name: "Black_and_White",
    is_stock: true,
    rating: 3.3,
    reviews: 5,
    description:
      "Silkscreen illustration of a man head portrait black mask.",
    trending: false,
    size: 12,
    img: "/assets/images/products-images/Black1.avif",
  },
  {
    _id: uuid(),
    name: "Albescent Ebony",
    original_price: 1199,
    discounted_price: 1099,
    category_name: "Black_and_White",
    is_stock: true,
    rating: 3.4,
    reviews: 11,
    description:
      "Beauty face black woman hyper realistic portrait african girl.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/Black2.jpg",
  },
  {
    _id: uuid(),
    name: "Imploration",
    original_price: 1099,
    discounted_price: 999,
    category_name: "Black_and_White",
    is_stock: true,
    rating: 4.5,
    reviews: 22,
    description:
      "Make a statement with our Black and White Art. These pieces command attention with their dramatic use of light and shadow, creating a captivating focal point in any room.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/Black3.avif",
  },
  {
    _id: uuid(),
    name: "Tribal Shadow",
    original_price: 499,
    discounted_price: 399,
    category_name: "Black_and_White",
    is_stock: true,
    rating: 4.2,
    reviews: 97,
    description:
      "Beautiful african woman monochrome portrait.",
    trending: false,
    size: 5,
    img: "/assets/images/products-images/Black4.avif",
  },
  {
    _id: uuid(),
    name: "Future Vision",
    original_price: 399,
    discounted_price: 299,
    category_name: "Black_and_White",
    is_stock: false,
    rating: 4.3,
    reviews: 245,
    description:
      "Discrimination Fight Racism black lives matter",
    trending: true,
    size: 7,
    img: "/assets/images/products-images/Black5.jpg",
  },
  {
    _id: uuid(),
    name: "Nightshade charm",
    original_price: 299,
    discounted_price: 199,
    category_name: "Black_and_White",
    is_stock: true,
    rating: 2.9,
    reviews: 43,
    description:
      "A woman with a tattoo on her back is shown with a drawing of a woman.",
    trending: true,
    size: 10,
    img: "/assets/images/products-images/Black6.jpg",
  },

  {
    _id: uuid(),
    name: "A.P-Potrait",
    original_price: 2099,
    discounted_price: 1999,
    category_name: "Pastel_Colors",
    is_stock: true,
    rating: 3.3,
    reviews: 99,
    description:
      "African woman a portrait from old Central African money.",
    trending: false,
    size: 8,
    img: "/assets/images/products-images/Pastel1.avif",
  },
  {
    _id: uuid(),
    name: "Rainbow Queen",
    original_price: 1499,
    discounted_price: 1399,
    category_name: "Pastel_Colors",
    is_stock: true,
    rating: 1.4,
    reviews: 109,
    description:
      "A poster of a woman with a colorful headdress.",
    trending: false,
    size: 7,
    img: "/assets/images/products-images/Pastel2.jpg",
  },

  {
    _id: uuid(),
    name: "Arafed",
    original_price: 1799,
    discounted_price: 1899,
    category_name: "Pastel_Colors",
    is_stock: false,
    rating: 4.3,
    reviews: 2133,
    description:
      "Arafed image of a woman in a colorful dress standing in front of a painting.",
    trending: false,
    size: 11,
    img: "/assets/images/products-images/Pastel3.jpg",
  },
  {
    _id: uuid(),
    name: "Sunset Overlooking",
    original_price: 159,
    discounted_price: 99,
    category_name: "Pastel_Colors",
    is_stock: true,
    rating: 3.5,
    reviews: 34,
    description:
      "Rendering of summer digital art illustration.",
    trending: false,
    size: 12,
    img: "/assets/images/products-images/Pastel4.avif",
  },
  {
    _id: uuid(),
    name: "Pottery Palette",
    original_price: 199,
    discounted_price: 99,
    category_name: "Pastel_Colors",
    is_stock: true,
    rating: 3.4,
    reviews: 689,
    description:
      "Digital art style pottery illustration.",
    trending: true,
    size: 11,
    img: "/assets/images/products-images/Pastel5.avif",
  },
  {
    _id: uuid(),
    name: "Sisterhood",
    original_price: 1299,
    discounted_price: 1199,
    category_name: "Pastel_Colors",
    is_stock: true,
    rating: 4.0,
    reviews: 36,
    description:
      "Witnessing the bond of sisterhood.",
    trending: false,
    size: 10,
    img: "/assets/images/products-images/Pastel6.avif",
  },
  {
    _id: uuid(),
    name: "Tropical Shade",
    original_price: 1899,
    discounted_price: 1799,
    category_name: "Oil_Painting",
    is_stock: true,
    rating: 4.2,
    reviews: 67,
    description:
      "World health day celebration with healthy food.",
    trending: false,
    size: 9,
    img: "/assets/images/products-images/Oil7.jpg",
  },
  {
    _id: uuid(),
    name: "Afro Jade",
    original_price: 1699,
    discounted_price: 1599,
    category_name: "Digital_Painting",
    is_stock: true,
    rating: 4.3,
    reviews: 109,
    description:
      "Serzana afeos music and sounds in the style of pop colorism colorful animations light green and dark gold bold and vibrant primary colors.",
    trending: true,
    size: 6,
    img: "/assets/images/products-images/Digital7.avif",
  },
  {
    _id: uuid(),
    name: "Retrochic",
    original_price: 899,
    discounted_price: 799,
    category_name: "Realism",
    is_stock: true,
    rating: 4.7,
    reviews: 235,
    description:
      "Painting of a woman's portrait.",
    trending: true,
    size: 8,
    img: "/assets/images/products-images/Realism7.avif",
  },
  {
    _id: uuid(),
    name: "Ascension",
    original_price: 599,
    discounted_price: 499,
    category_name: "3D_Art",
    is_stock: false,
    rating: 3.7,
    reviews: 543,
    description:
      "A 3D poster for Black History Month that showcases a virtual sculpture of the African continent.",
    trending: true,
    size: 11,
    img: "/assets/images/products-images/3D7.jpg",
  },
  {
    _id: uuid(),
    name: "Braided Beauty",
    original_price: 399,
    discounted_price: 299,
    category_name: "Pixel_Art",
    is_stock: true,
    rating: 3.5,
    reviews: 69,
    description:
      "Pixelated portrait of a woman with colorful braids and hoop earrings.",
    trending: false,
    size: 8,
    img: "/assets/images/products-images/Pixel7.avif",
  },
];
